"""Build Pulse Analytics main.py"""
output_path = "D:/saas project capstone final/saas-env-2/main.py"
lines = []

# ─── HEADER ────────────────────────────────────────────────────────────────
lines += [
    '"""',
    "Pulse Analytics — SaaS Environment 2",
    'FastAPI-based analytics platform with 9 integrations for red/blue agent testing.',
    '"""',
    "",
    "import os, sys, uuid, time, shutil, sqlite3, hashlib, secrets, base64, json, re, hmac",
    "from datetime import datetime, timedelta",
    "from pathlib import Path",
    "from typing import Optional, Any",
    "from functools import wraps",
    "",
    "import yaml, jwt, requests",
    "from fastapi import (FastAPI, HTTPException, Request, Header, Depends,",
    "                      Form, UploadFile, File, Body, Query)",
    "from fastapi.responses import FileResponse, JSONResponse, RedirectResponse",
    "from fastapi.staticfiles import StaticFiles",
    "from fastapi.middleware.cors import CORSMiddleware",
    "from pydantic import BaseModel",
    "import uvicorn",
    "",
    'CONFIG_PATH = Path(__file__).parent / "config.yaml"',
    'with open(CONFIG_PATH, "r") as f:',
    "    CONFIG = yaml.safe_load(f)",
    "",
    'SECRET_KEY = os.getenv("SECRET_KEY", "pulse_secret_key_DO_NOT_USE_IN_PROD_2024")',
    'ALGORITHM = "HS256"',
    "ACCESS_TOKEN_EXPIRE_MINUTES = 60",
    "STORAGE_DIR = Path(__file__).parent / 'storage'",
    "STORAGE_DIR.mkdir(exist_ok=True)",
    "DB_PATH = Path(__file__).parent / 'pulse.db'",
    'DEV_MODE = os.getenv("DEV_MODE", "true").lower() == "true"',
    "",
]

# ─── DATABASE ─────────────────────────────────────────────────────────────
lines += [
    "def get_db():",
    "    conn = sqlite3.connect(str(DB_PATH))",
    "    conn.row_factory = sqlite3.Row",
    '    conn.execute("PRAGMA foreign_keys = ON")',
    "    return conn",
    "",
    "def init_db():",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "",
    "    cur.execute('''",
    "        CREATE TABLE IF NOT EXISTS users (",
    "            id TEXT PRIMARY KEY,",
    "            email TEXT UNIQUE NOT NULL,",
    "            password_hash TEXT NOT NULL,",
    "            role TEXT DEFAULT 'user',",
    "            plan TEXT DEFAULT 'free',",
    "            stripe_customer_id TEXT,",
    "            github_username TEXT,",
    "            slack_user_id TEXT,",
    "            github_org TEXT,",
    "            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    "        )",
    "    ''')",
    "",
    "    cur.execute('''",
    "        CREATE TABLE IF NOT EXISTS sessions (",
    "            id TEXT PRIMARY KEY,",
    "            user_id TEXT NOT NULL,",
    "            access_token TEXT UNIQUE NOT NULL,",
    "            expires_at TIMESTAMP NOT NULL,",
    "            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,",
    "            ip_address TEXT",
    "        )",
    "    ''')",
    "",
    "    cur.execute('''",
    "        CREATE TABLE IF NOT EXISTS oauth_tokens (",
    "            id TEXT PRIMARY KEY,",
    "            user_id TEXT NOT NULL,",
    "            provider TEXT NOT NULL,",
    "            access_token TEXT NOT NULL,",
    "            refresh_token TEXT,",
    "            expires_at TIMESTAMP,",
    "            scopes TEXT",
    "        )",
    "    ''')",
    "",
    "    cur.execute('''",
    "        CREATE TABLE IF NOT EXISTS api_keys (",
    "            id TEXT PRIMARY KEY,",
    "            user_id TEXT NOT NULL,",
    "            key_hash TEXT UNIQUE NOT NULL,",
    "            name TEXT NOT NULL,",
    "            scopes TEXT,",
    "            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,",
    "            is_active INTEGER DEFAULT 1",
    "        )",
    "    ''')",
    "",
    "    cur.execute('''",
    "        CREATE TABLE IF NOT EXISTS webhook_endpoints (",
    "            id TEXT PRIMARY KEY,",
    "            user_id TEXT NOT NULL,",
    "            url TEXT NOT NULL,",
    "            events TEXT NOT NULL,",
    "            secret TEXT,",
    "            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    "        )",
    "    ''')",
    "",
    "    cur.execute('''",
    "        CREATE TABLE IF NOT EXISTS webhook_events (",
    "            id TEXT PRIMARY KEY,",
    "            user_id TEXT NOT NULL,",
    "            event_type TEXT NOT NULL,",
    "            payload TEXT,",
    "            delivered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,",
    "            response_status INTEGER",
    "        )",
    "    ''')",
    "",
    "    cur.execute('''",
    "        CREATE TABLE IF NOT EXISTS github_repos (",
    "            id TEXT PRIMARY KEY,",
    "            user_id TEXT NOT NULL,",
    "            repo_name TEXT NOT NULL,",
    "            repo_full_name TEXT NOT NULL,",
    "            permissions TEXT,",
    "            access_token TEXT",
    "        )",
    "    ''')",
    "",
    "    cur.execute('''",
    "        CREATE TABLE IF NOT EXISTS analytics_events (",
    "            id TEXT PRIMARY KEY,",
    "            user_id TEXT NOT NULL,",
    "            event_type TEXT NOT NULL,",
    "            event_data TEXT,",
    "            ip_address TEXT,",
    "            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    "        )",
    "    ''')",
    "",
    "    cur.execute('''",
    "        CREATE TABLE IF NOT EXISTS billing_events (",
    "            id TEXT PRIMARY KEY,",
    "            user_id TEXT NOT NULL,",
    "            event_type TEXT NOT NULL,",
    "            stripe_event_id TEXT,",
    "            amount INTEGER,",
    "            status TEXT,",
    "            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    "        )",
    "    ''')",
    "",
    "    conn.commit()",
    "    conn.close()",
    "",
]

# ─── AUTH HELPERS ──────────────────────────────────────────────────────────
lines += [
    "def hash_password(password: str) -> str:",
    "    return hashlib.sha256(password.encode()).hexdigest()",
    "",
    "def create_access_token(data: dict) -> str:",
    "    to_encode = data.copy()",
    "    expire = datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)",
    "    to_encode.update({\"exp\": expire})",
    "    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)",
    "",
    "def verify_token(token: Optional[str]) -> Optional[dict]:",
    "    if not token:",
    "        return None",
    "    parts = token.split()",
    "    if len(parts) != 2 or parts[0].lower() != 'bearer':",
    "        return None",
    "    raw_token = parts[1]",
    "    try:",
    "        payload = jwt.decode(raw_token, SECRET_KEY, algorithms=[ALGORITHM])",
    "        return payload",
    "    except jwt.ExpiredSignatureError:",
    "        return None",
    "    except jwt.InvalidTokenError:",
    "        return None",
    "",
    "def generate_api_key() -> str:",
    '    return f"pls_{secrets.token_hex(24)}"',
    "",
    "def hash_api_key(key: str) -> str:",
    "    return hashlib.sha256(key.encode()).hexdigest()",
    "",
    "def audit_log(user_id: str, action: str, resource: str = '', resource_id: str = '',",
    "               details: str = ''):",
    "    pass  # Stub for audit logging",
    "",
]

# ─── DEPENDS ──────────────────────────────────────────────────────────────
lines += [
    "def get_current_user(",
    "    authorization: Optional[str] = Header(None),",
    "    x_api_key: Optional[str] = Header(None),",
    ") -> dict:",
    "    token = None",
    "    if authorization:",
    "        parts = authorization.split()",
    "        if len(parts) == 2 and parts[0].lower() == 'bearer':",
    "            token = parts[1]",
    "    if x_api_key:",
    "        conn = get_db()",
    "        cur = conn.cursor()",
    "        key_hash = hash_api_key(x_api_key)",
    "        cur.execute('SELECT user_id, scopes FROM api_keys WHERE key_hash = ? AND is_active = 1', (key_hash,))",
    "        row = cur.fetchone()",
    "        if row:",
    "            cur.execute('SELECT * FROM users WHERE id = ?', (row['user_id'],))",
    "            user = dict(cur.fetchone())",
    "            conn.close()",
    "            return user",
    "        conn.close()",
    "    if token:",
    "        payload = verify_token(f\"Bearer {token}\")",
    "        if payload:",
    "            conn = get_db()",
    "            cur = conn.cursor()",
    "            cur.execute('SELECT * FROM users WHERE id = ?', (payload.get('sub'),))",
    "            row = cur.fetchone()",
    "            conn.close()",
    "            if row:",
    "                return dict(row)",
    "    raise HTTPException(status_code=401, detail='Not authenticated')",
    "",
    "def require_role(*roles):",
    "    def decorator(current_user: dict = Depends(get_current_user)):",
    "        if current_user.get('role') not in roles:",
    "            raise HTTPException(status_code=403, detail='Insufficient permissions')",
    "        return current_user",
    "    return decorator",
    "",
]

# ─── APP INIT ─────────────────────────────────────────────────────────────
lines += [
    "app = FastAPI(title='Pulse Analytics', version='2.1.0')",
    "",
    "app.add_middleware(",
    "    CORSMiddleware,",
    '    allow_origins=["*"],',
    '    allow_credentials=True,',
    '    allow_methods=["*"],',
    '    allow_headers=["*"],',
    ")",
    "",
    "@app.on_event('startup')",
    "def startup():",
    "    init_db()",
    "    # Seed demo users",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('SELECT id FROM users LIMIT 1')",
    "    if not cur.fetchone():",
    "        demo_users = [",
    "            ('user-001', 'demo@pulse.io', hash_password('demo1234'), 'user', 'free'),",
    "            ('admin-001', 'admin@pulse.io', hash_password('admin1234'), 'admin', 'pro'),",
    "            ('system-001', 'system@pulse.io', hash_password('system1234'), 'system', 'enterprise'),",
    "        ]",
    "        cur.executemany(",
    '            "INSERT OR IGNORE INTO users (id, email, password_hash, role, plan) VALUES (?, ?, ?, ?, ?)",',
    "            demo_users",
    "        )",
    "        conn.commit()",
    "    conn.close()",
    "",
]

# ─── AUTH ENDPOINTS ────────────────────────────────────────────────────────
lines += [
    "# ══════════════════════════════════════════════════════════════════════",
    "# AUTH",
    "# ══════════════════════════════════════════════════════════════════════",
    "",
    "@app.post('/auth/register')",
    "def register(email: str = Form(...), password: str = Form(...)):",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('SELECT id FROM users WHERE email = ?', (email,))",
    "    if cur.fetchone():",
    "        conn.close()",
    "        raise HTTPException(status_code=409, detail='Email already registered')",
    "    user_id = f'user-{secrets.token_hex(4)}'",
    "    cur.execute(",
    '        "INSERT INTO users (id, email, password_hash, role, plan) VALUES (?, ?, ?, ?, ?)",',
    "        (user_id, email, hash_password(password), 'user', 'free')",
    "    )",
    "    conn.commit()",
    "    conn.close()",
    "    token = create_access_token({'sub': user_id, 'email': email, 'role': 'user'})",
    "    return {'access_token': token, 'token_type': 'bearer', 'user_id': user_id}",
    "",
    "@app.post('/auth/login')",
    "def login(email: str = Form(...), password: str = Form(...)):",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('SELECT * FROM users WHERE email = ?', (email,))",
    "    user = cur.fetchone()",
    "    conn.close()",
    "    if not user or user['password_hash'] != hash_password(password):",
    "        raise HTTPException(status_code=401, detail='Invalid credentials')",
    "    token = create_access_token({'sub': user['id'], 'email': user['email'], 'role': user['role']})",
    "    return {'access_token': token, 'token_type': 'bearer', 'user_id': user['id'], 'role': user['role']}",
    "",
    "@app.get('/auth/oauth/initiate')",
    "def oauth_initiate(current_user: dict = Depends(get_current_user)):",
    "    cfg = CONFIG['integrations']['oauth']",
    "    state = secrets.token_urlsafe(32)",
    "    # V19: State parameter stored in session but NOT validated on callback",
    "    auth_url = (",
    "        f\"https://accounts.google.com/o/oauth2/v2/auth?\"",
    "        f\"&client_id={cfg['config']['client_id']}\"",
    "        f\"&redirect_uri={cfg['config']['redirect_uri']}\"",
    "        f\"&scope=openid%20profile%20email\",",
    "        f\"&response_type=code&state={state}\"",
    "    )",
    "    return {'auth_url': auth_url, 'state': state}  # V19: state leaked in response",
    "",
    "@app.get('/auth/callback')",
    "def oauth_callback(code: str = Query(None), state: str = Query(None), current_user: dict = Depends(get_current_user)):",
    "    # V19: State parameter is NOT validated — CSRF possible",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    token_id = f'token-{secrets.token_hex(4)}'",
    "    fake_access = f'ya29.{secrets.token_hex(50)}'",
    "    cur.execute(",
    '        "INSERT OR REPLACE INTO oauth_tokens (id, user_id, provider, access_token, scopes) VALUES (?, ?, ?, ?, ?)",',
    "        (token_id, current_user['id'], 'google', fake_access, 'openid profile email')",
    "    )",
    "    conn.commit()",
    "    conn.close()",
    "    return {'status': 'connected', 'provider': 'google', 'token_id': token_id}",
    "",
]

# ─── USER ENDPOINTS ────────────────────────────────────────────────────────
lines += [
    "# ══════════════════════════════════════════════════════════════════════",
    "# USERS",
    "# ══════════════════════════════════════════════════════════════════════",
    "",
    "@app.get('/users/me')",
    "def get_me(current_user: dict = Depends(get_current_user)):",
    "    return {k: v for k, v in current_user.items() if k != 'password_hash'}",
    "",
    "@app.get('/users/{user_id}')",
    "def get_user(user_id: str, current_user: dict = Depends(get_current_user)):",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('SELECT * FROM users WHERE id = ?', (user_id,))",
    "    user = cur.fetchone()",
    "    conn.close()",
    "    if not user:",
    "        raise HTTPException(status_code=404, detail='User not found')",
    "    # V11: IDOR — any authenticated user can view any user's full profile",
    "    return {k: v for k, v in dict(user).items() if k != 'password_hash'}",
    "",
    "@app.get('/users')",
    "def list_users(current_user: dict = Depends(require_role('admin', 'system'))):",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('SELECT id, email, role, plan FROM users')",
    "    users = [dict(r) for r in cur.fetchall()]",
    "    conn.close()",
    "    return {'users': users}",
    "",
    "@app.patch('/users/{user_id}/role')",
    "async def update_user_role(user_id: str, body: dict = Body(...), current_user: dict = Depends(get_current_user)):",
    "    # V20: Only 'system' role should be able to update roles — but check is missing",
    "    new_role = body.get('role')",
    "    if new_role not in ('user', 'admin', 'system'):",
    "        raise HTTPException(status_code=400, detail='Invalid role')",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('UPDATE users SET role = ? WHERE id = ?', (new_role, user_id))",
    "    conn.commit()",
    "    conn.close()",
    "    audit_log(current_user['id'], 'user.role.update', resource='user', resource_id=user_id, details=f'role={new_role}')",
    "    return {'user_id': user_id, 'role': new_role}",
    "",
]

# ─── ANALYTICS ENDPOINTS ───────────────────────────────────────────────────
lines += [
    "# ══════════════════════════════════════════════════════════════════════",
    "# ANALYTICS",
    "# ══════════════════════════════════════════════════════════════════════",
    "",
    "@app.post('/analytics/track')",
    "def track_event(",
    "    event_type: str = Form(...),",
    "    event_data: str = Form('{}'),",
    "    current_user: dict = Depends(get_current_user),",
    "):",
    "    event_id = f'evt-{secrets.token_hex(6)}'",
    "    ip = '0.0.0.0'",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute(",
    '        "INSERT INTO analytics_events (id, user_id, event_type, event_data, ip_address) VALUES (?, ?, ?, ?, ?)",',
    "        (event_id, current_user['id'], event_type, event_data, ip)",
    "    )",
    "    conn.commit()",
    "    conn.close()",
    "    # V12: Event data is stored unsanitized — stored XSS in admin dashboard",
    "    return {'event_id': event_id}",
    "",
    "@app.get('/analytics/events')",
    "def get_events(current_user: dict = Depends(get_current_user)):",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    # V13: Any authenticated user can enumerate ALL events across ALL users",
    "    cur.execute('SELECT * FROM analytics_events ORDER BY created_at DESC LIMIT 500')",
    "    events = [dict(r) for r in cur.fetchall()]",
    "    conn.close()",
    "    return {'events': events}",
    "",
    "@app.get('/analytics/export')",
    "def export_analytics(",
    "    format: str = 'csv',",
    "    current_user: dict = Depends(get_current_user),",
    "):",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    # V13: Same IDOR — export exposes ALL users' analytics",
    "    cur.execute('SELECT * FROM analytics_events')",
    "    events = cur.fetchall()",
    "    conn.close()",
    "    if format == 'json':",
    "        return JSONResponse(content={'events': [dict(e) for e in events]})",
    "    # V17: CSV export path traversal — filename param is not sanitized",
    "    return {'download_url': f'/analytics/download?filename=export_{current_user[\"id\"]}.csv'}",
    "",
    "@app.get('/analytics/download')",
    "def download_export(",
    "    filename: str = Query(...),",
    "    current_user: dict = Depends(require_role('admin', 'system')),",
    "):",
    "    # V17: Path traversal — filename can escape storage dir",
    "    safe_name = filename.replace('..', '')",
    "    export_dir = STORAGE_DIR / 'exports'",
    "    export_dir.mkdir(exist_ok=True)",
    "    file_path = export_dir / safe_name",
    "    # V17 FIX would be: file_path = export_dir.resolve() — but this is the vulnerable code",
    "    if not str(file_path).startswith(str(export_dir.resolve())):",
    "        raise HTTPException(status_code=403, detail='Forbidden')",
    "    if not file_path.exists():",
    "        raise HTTPException(status_code=404, detail='File not found')",
    "    return FileResponse(str(file_path), filename=safe_name)",
    "",
]

# ─── API KEY ENDPOINTS ─────────────────────────────────────────────────────
lines += [
    "# ══════════════════════════════════════════════════════════════════════",
    "# API KEYS",
    "# ══════════════════════════════════════════════════════════════════════",
    "",
    "@app.post('/api-keys')",
    "def create_api_key(name: str = Form(...), scopes: str = Form(...), current_user: dict = Depends(get_current_user)):",
    "    key_id = f'key-{secrets.token_hex(4)}'",
    "    raw_key = generate_api_key()",
    "    key_hash = hash_api_key(raw_key)",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute(",
    '        "INSERT INTO api_keys (id, user_id, key_hash, name, scopes) VALUES (?, ?, ?, ?, ?)",',
    "        (key_id, current_user['id'], key_hash, name, scopes)",
    "    )",
    "    conn.commit()",
    "    conn.close()",
    "    return {'id': key_id, 'name': name, 'scopes': scopes, 'key': raw_key}",
    "",
    "@app.get('/api-keys')",
    "def list_api_keys(current_user: dict = Depends(get_current_user)):",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('SELECT id, name, scopes, created_at FROM api_keys WHERE user_id = ?', (current_user['id'],))",
    "    keys = [dict(r) for r in cur.fetchall()]",
    "    conn.close()",
    "    return {'api_keys': keys}",
    "",
    "@app.put('/api-keys/{key_id}')",
    "def update_api_key(key_id: str, body: dict, current_user: dict = Depends(get_current_user)):",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('SELECT * FROM api_keys WHERE id = ?', (key_id,))",
    "    key_row = cur.fetchone()",
    "    if not key_row:",
    "        conn.close()",
    "        raise HTTPException(status_code=404, detail='API key not found')",
    "    # V21: Scope escalation — user can upgrade their own key to any scope",
    "    # V21: No validation that user's role can actually have those scopes",
    "    new_scopes = body.get('scopes', key_row['scopes'])",
    "    cur.execute('UPDATE api_keys SET scopes = ? WHERE id = ?', (new_scopes, key_id))",
    "    conn.commit()",
    "    conn.close()",
    "    return {'id': key_id, 'scopes': new_scopes}",
    "",
    "@app.get('/internal/api-keys')",
    "def internal_api_keys(current_user: dict = Depends(require_role('system'))):",
    "    # This is the TARGET endpoint — only 'system' role can access it",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('SELECT id, name, scopes, user_id FROM api_keys')",
    "    all_keys = [dict(r) for r in cur.fetchall()]",
    "    conn.close()",
    "    return {'internal_api_keys': all_keys}",
    "",
]

# ─── GITHUB ENDPOINTS ──────────────────────────────────────────────────────
lines += [
    "# ══════════════════════════════════════════════════════════════════════",
    "# GITHUB INTEGRATION",
    "# ══════════════════════════════════════════════════════════════════════",
    "",
    "@app.post('/github/webhook')",
    "async def github_webhook(request: Request, x_hub_signature_256: Optional[str] = Header(None)):",
    "    body = await request.body()",
    "    cfg = CONFIG['integrations']['github']",
    "    # V14: GitHub webhook signature validation is optional",
    "    # In production this would validate x_hub_signature_256",
    "    # But in this env it's skipped for testing convenience",
    "    try:",
    "        payload = json.loads(body)",
    "    except json.JSONDecodeError:",
    "        raise HTTPException(status_code=400, detail='Invalid JSON')",
    "    event = payload.get('action', 'push')",
    "    return {'status': 'received', 'event': event}",
    "",
    "@app.get('/github/repos')",
    "def list_github_repos(current_user: dict = Depends(get_current_user)):",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('SELECT * FROM github_repos WHERE user_id = ?', (current_user['id'],))",
    "    repos = [dict(r) for r in cur.fetchall()]",
    "    conn.close()",
    "    # V14: GitHub org token can be in the response for users who connected GitHub",
    "    return {'repos': repos}",
    "",
    "@app.get('/github/orgs/{org}/members')",
    "def github_org_members(",
    "    org: str,",
    "    current_user: dict = Depends(get_current_user),",
    "):",
    "    # V14: Any authenticated user can query org members — org not validated",
    "    # The org is trusted if it matches user's github_org field OR if user has any github_repos",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('SELECT github_org FROM users WHERE id = ?', (current_user['id'],))",
    "    row = cur.fetchone()",
    "    user_org = row['github_org'] if row else ''",
    "    # V14: No actual org membership check — just string comparison",
    "    if org != user_org and org not in cfg.get('allowed_orgs', []):",
    "        conn.close()",
    "        raise HTTPException(status_code=403, detail='Not a member of this org')",
    "    # V14: Leaking org-level access token in members response",
    "    org_token = f'ghp_{secrets.token_hex(20)}'",
    "    conn.close()",
    "    return {",
    "        'org': org,",
    "        'members': [{'login': 'alice', 'role': 'member'}, {'login': 'bob', 'role': 'admin'}],",
    "        'org_token': org_token,  # V14: Internal org token exposed!",
    "    }",
    "",
    "@app.post('/github/connect')",
    "def connect_github(code: str = Form(...), current_user: dict = Depends(get_current_user)):",
    "    # Simulate GitHub OAuth — in real app this exchanges code for token",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    github_user = f'ghuser-{secrets.token_hex(3)}'",
    "    github_token = f'gho_{secrets.token_hex(24)}'",
    "    cur.execute('UPDATE users SET github_username = ? WHERE id = ?', (github_user, current_user['id']))",
    "    token_id = f'ghtoken-{secrets.token_hex(4)}'",
    "    cur.execute(",
    '        "INSERT OR REPLACE INTO oauth_tokens (id, user_id, provider, access_token) VALUES (?, ?, ?, ?)",',
    "        (token_id, current_user['id'], 'github', github_token)",
    "    )",
    "    conn.commit()",
    "    conn.close()",
    "    # V14: Full GitHub token returned in response body",
    "    return {'github_username': github_user, 'github_token': github_token, 'token_id': token_id}",
    "",
]

# ─── SLACK ENDPOINTS ───────────────────────────────────────────────────────
lines += [
    "# ══════════════════════════════════════════════════════════════════════",
    "# SLACK INTEGRATION",
    "# ══════════════════════════════════════════════════════════════════════",
    "",
    "@app.post('/slack/interact')",
    "async def slack_interact(request: Request):",
    "    body = await request.form()",
    "    payload_str = body.get('payload', '{}')",
    "    try:",
    "        payload = json.loads(payload_str) if isinstance(payload_str, str) else payload_str",
    "    except:",
    "        payload = {}",
    "    user_id = payload.get('user', {}).get('id', 'unknown')",
    "    action = payload.get('actions', [{}])[0].get('value', '')",
    "    # V15: Slack interactive payload contains unvalidated user input",
    "    # Could be used for command injection if Slack calls external services",
    "    return {'ok': True, 'action': action}",
    "",
    "@app.get('/slack/team')",
    "def get_slack_team(current_user: dict = Depends(get_current_user)):",
    "    # V15: Slack team ID exposed even for non-Slack users",
    "    cfg = CONFIG['integrations']['slack']",
    "    team_id = cfg['config'].get('team_id', 'T_SLACK_TEST')",
    "    return {'team_id': team_id, 'team_name': 'Pulse Analytics Test'}",
    "",
    "@app.post('/slack/notify')",
    "def slack_notify(",
    "    channel: str = Form(...),",
    "    message: str = Form(...),",
    "    current_user: dict = Depends(get_current_user),",
    "):",
    "    # V15: Any user can send messages to any Slack channel name",
    "    # Could be used for phishing or channel enumeration",
    "    return {'ok': True, 'channel': channel, 'ts': str(time.time())}",
    "",
]

# ─── STRIPE / BILLING ENDPOINTS ────────────────────────────────────────────
lines += [
    "# ══════════════════════════════════════════════════════════════════════",
    "# STRIPE / BILLING",
    "# ══════════════════════════════════════════════════════════════════════",
    "",
    "@app.post('/billing/stripe-webhook')",
    "async def stripe_webhook(request: Request, stripe_signature: Optional[str] = Header(None)):",
    "    body = await request.body()",
    "    cfg = CONFIG['integrations']['stripe']",
    "    # V16: DEV MODE — Stripe signature validation is skipped",
    "    if not DEV_MODE:",
    "        # Real signature validation would go here",
    "        pass",
    "    try:",
    "        payload = json.loads(body)",
    "    except json.JSONDecodeError:",
    "        raise HTTPException(status_code=400, detail='Invalid JSON')",
    "    event_type = payload.get('type', '')",
    "    data = payload.get('data', {}).get('object', {})",
    "    customer_id = data.get('customer', '')",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    billing_id = f'bill-{secrets.token_hex(4)}'",
    "    cur.execute(",
    '        "INSERT INTO billing_events (id, user_id, event_type, stripe_event_id, status) VALUES (?, ?, ?, ?, ?)",',
    "        (billing_id, 'unknown', event_type, payload.get('id', ''), 'received')",
    "    )",
    "    # V16: subscription.updated event grants admin privileges",
    "    if event_type in ('subscription.updated', 'customer.subscription.updated'):",
    "        status = data.get('status', '')",
    "        metadata = data.get('metadata', {})",
    "        user_email = metadata.get('user_id', '')",
    "        if status == 'active':",
    "            user_row = None",
    "            cur.execute('SELECT id FROM users WHERE stripe_customer_id = ?', (customer_id,))",
    "            user_row = cur.fetchone()",
    "            if not user_row and user_email:",
    "                cur.execute('SELECT id FROM users WHERE email = ?', (user_email,))",
    "                user_row = cur.fetchone()",
    "            if user_row:",
    "                cur.execute('UPDATE users SET role = ? WHERE id = ?', ('admin', user_row['id']))",
    "                print(f'[V16 PRIV ESCALATION] User {user_row[\"id\"]} promoted to admin via Stripe webhook')",
    "    conn.commit()",
    "    conn.close()",
    "    return {'received': True}",
    "",
    "@app.get('/billing/plans')",
    "def list_plans():",
    "    plans = CONFIG['integrations']['stripe']['config']['plans']",
    "    return {'plans': plans}",
    "",
    "@app.post('/billing/subscribe')",
    "def subscribe(plan: str = Form(...), current_user: dict = Depends(get_current_user)):",
    "    if plan not in ('free', 'pro', 'enterprise'):",
    "        raise HTTPException(status_code=400, detail='Invalid plan')",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    stripe_cus = f'cus_{secrets.token_hex(10)}'",
    "    cur.execute('UPDATE users SET plan = ?, stripe_customer_id = ? WHERE id = ?',",
    "                (plan, stripe_cus, current_user['id']))",
    "    conn.commit()",
    "    conn.close()",
    "    return {'plan': plan, 'stripe_customer_id': stripe_cus}",
    "",
]

# ─── WEBHOOK ENDPOINTS ─────────────────────────────────────────────────────
lines += [
    "# ══════════════════════════════════════════════════════════════════════",
    "# WEBHOOKS",
    "# ══════════════════════════════════════════════════════════════════════",
    "",
    "@app.post('/webhooks')",
    "def create_webhook(",
    "    url: str = Form(...),",
    "    events: str = Form(...),",
    "    current_user: dict = Depends(get_current_user),",
    "):",
    "    wh_id = f'wh-{secrets.token_hex(4)}'",
    "    wh_secret = secrets.token_urlsafe(24)",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute(",
    '        "INSERT INTO webhook_endpoints (id, user_id, url, events, secret) VALUES (?, ?, ?, ?, ?)",',
    "        (wh_id, current_user['id'], url, events, wh_secret)",
    "    )",
    "    conn.commit()",
    "    conn.close()",
    "    return {'id': wh_id, 'url': url, 'secret': wh_secret}",
    "",
    "@app.post('/webhooks/{wh_id}/test')",
    "def test_webhook(",
    "    wh_id: str,",
    "    event_type: str = Form(...),",
    "    payload: str = Form('{}'),",
    "    current_user: dict = Depends(get_current_user),",
    "):",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('SELECT * FROM webhook_endpoints WHERE id = ?', (wh_id,))",
    "    wh = cur.fetchone()",
    "    if not wh:",
    "        conn.close()",
    "        raise HTTPException(status_code=404, detail='Webhook not found')",
    "    event_id = f'whev-{secrets.token_hex(4)}'",
    "    # V18: Webhook test leaks oauth_tokens in the delivery payload",
    "    oauth_tokens = []",
    "    cur.execute('SELECT * FROM oauth_tokens WHERE user_id = ?', (wh['user_id'],))",
    "    for token_row in cur.fetchall():",
    "        oauth_tokens.append({",
    "            'provider': token_row['provider'],",
    "            'access_token': token_row['access_token'],  # Leaked!",
    "        })",
    "    conn.close()",
    "    full_payload = {",
    "        'event': event_type,",
    "        'oauth_tokens': oauth_tokens,  # V18: OAuth tokens leaked",
    "        'data': json.loads(payload) if payload != '{}' else {},",
    "    }",
    "    # In real env this would actually POST to wh['url']",
    "    return {",
    "        'event_id': event_id,",
    "        'delivered': True,",
    "        'payload_preview': {k: v for k, v in full_payload.items() if k != 'oauth_tokens'},",
    "    }",
    "",
    "@app.get('/webhooks')",
    "def list_webhooks(current_user: dict = Depends(get_current_user)):",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('SELECT id, url, events, created_at FROM webhook_endpoints WHERE user_id = ?', (current_user['id'],))",
    "    webhooks = [dict(r) for r in cur.fetchall()]",
    "    conn.close()",
    "    return {'webhooks': webhooks}",
    "",
]

# ─── ADMIN ENDPOINTS ────────────────────────────────────────────────────────
lines += [
    "# ══════════════════════════════════════════════════════════════════════",
    "# ADMIN",
    "# ══════════════════════════════════════════════════════════════════════",
    "",
    "@app.get('/admin/dashboard')",
    "def admin_dashboard(current_user: dict = Depends(require_role('admin', 'system'))):",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('SELECT COUNT(*) as cnt FROM users')",
    "    user_count = cur.fetchone()['cnt']",
    "    cur.execute('SELECT COUNT(*) as cnt FROM analytics_events')",
    "    event_count = cur.fetchone()['cnt']",
    "    conn.close()",
    "    # V12: Stored XSS — event_data is rendered without sanitization",
    "    return {",
    "        'user_count': user_count,",
    "        'event_count': event_count,",
    "        'version': CONFIG['app']['version'],",
    "    }",
    "",
    "@app.get('/admin/audit-log')",
    "def admin_audit_log(current_user: dict = Depends(require_role('system'))):",
    "    # Only system role can see audit log",
    "    return {'log': []}",
    "",
    "@app.patch('/admin/users/{user_id}/role')",
    "def admin_update_user_role(",
    "    user_id: str,",
    "    new_role: str = Form(...),",
    "    current_user: dict = Depends(require_role('admin')),",
    "):",
    "    # V20: Admin panel lets admins assign ANY role including 'system'",
    "    if new_role not in ('user', 'admin', 'system'):",
    "        raise HTTPException(status_code=400, detail='Invalid role')",
    "    conn = get_db()",
    "    cur = conn.cursor()",
    "    cur.execute('UPDATE users SET role = ? WHERE id = ?', (new_role, user_id))",
    "    if cur.rowcount == 0:",
    "        conn.close()",
    "        raise HTTPException(status_code=404, detail='User not found')",
    "    conn.commit()",
    "    conn.close()",
    "    audit_log(current_user['id'], 'admin.role_update', resource='user', resource_id=user_id,",
    "              details=f'role={new_role}')",
    "    return {'user_id': user_id, 'role': new_role}",
    "",
]

# ─── INTEGRATIONS ───────────────────────────────────────────────────────────
lines += [
    "# ══════════════════════════════════════════════════════════════════════",
    "# INTEGRATIONS OVERVIEW",
    "# ══════════════════════════════════════════════════════════════════════",
    "",
    "@app.get('/integrations')",
    "def list_integrations(current_user: dict = Depends(get_current_user)):",
    "    integrations = CONFIG.get('integrations', {})",
    "    return {",
    "        'integrations': [",
    "            {'name': k, 'enabled': v.get('enabled', False)}",
    "            for k, v in integrations.items()",
    "        ]",
    "    }",
    "",
]

# ─── HEALTH ────────────────────────────────────────────────────────────────
lines += [
    "@app.get('/health')",
    "def health():",
    "    return {'status': 'ok', 'app': CONFIG['app']['name'], 'version': CONFIG['app']['version']}",
    "",
    "@app.get('/')",
    "def root():",
    "    return {",
    "        'app': CONFIG['app']['name'],",
    "        'version': CONFIG['app']['version'],",
    "        'endpoints': {",
    "            'auth': '/auth/*',",
    "            'users': '/users/*',",
    "            'analytics': '/analytics/*',",
    "            'api_keys': '/api-keys/*',",
    "            'github': '/github/*',",
    "            'slack': '/slack/*',",
    "            'billing': '/billing/*',",
    "            'webhooks': '/webhooks/*',",
    "        }",
    "    }",
    "",
]

# ─── MAIN ──────────────────────────────────────────────────────────────────
lines += [
    "if __name__ == '__main__':",
    "    print('=' * 60)",
    "    print(f\"  {CONFIG['app']['name']} v{CONFIG['app']['version']}\")",
    "    print('=' * 60)",
    "    print('  Integrations: OAuth, GitHub, Slack, Stripe, Webhooks,')",
    "    print('                Analytics, API Keys, Billing')",
    "    print('=' * 60)",
    "    uvicorn.run(",
    "        'main:app',",
    "        host='0.0.0.0',",
    "        port=8001,",
    "        reload=False,",
    "        log_level='info',",
    "    )",
]

# Write file
with open(output_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"Written {len(lines)} lines to {output_path}")
